version: 1
root:
    level: DEBUG
    handlers: [console, file]

formatters:
    standard:
        format: '%(asctime)s [%(levelname)s] [%(module)s] %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class : logging.StreamHandler
        formatter: standard
        stream: ext://sys.stdout
    file:
        class : logging.handlers.RotatingFileHandler
        formatter: standard
        filename: botlog.log
        backupCount: 24
        maxBytes: 1048576 #1MB
        encoding: 'UTF-8'